### ISSUE TITLE
Example model used in tutorial

### ISSUE THREAD

**Issue by nextbuddy** [FlailingFog/KK-Blender-Shader-Pack#18]
Is the final model (fbx) you used for demonstration in the [tutorial series](https://www.youtube.com/watch?v=xe5A8bOh2Mk&list=PLhiuav2SCuvd5eAOb3Ct1eovFAlgv-iwe&index=1) private?

**Comment by FlailingFog** [comment]
The model is from a game rip, so yes. 
If you want to make your own though, the actual card is from Pis on pixiv. It looks like they're okay with redistribution [so I've added it here](https://github.com/FlailingFog/KK-Blender-Shader-Pack/tree/master/wiki).

**Comment by nextbuddy** [comment]
Understandable. Thanks for sharing the card!
