### ISSUE TITLE
Armature not found errors

### ISSUE THREAD

**Issue by HarryBols** [FlailingFog/KK-Blender-Shader-Pack#21]
Anything involving the Armature says the a bone isn't found,also the cats importer isn't giving the fix model option or renaming anything, but idk if you could fix that

**Comment by FlailingFog** [comment]
CATS renames some objects and bones so if CATS isn't completely working then unfortunately anything can fail.
If you're on Blender 2.93, then try [using the development version of CATS](https://github.com/GiveMeAllYourCats/cats-blender-plugin/tree/development), else you'll have to import and fix the model using 2.92 or lower

**Comment by FlailingFog** [comment]
cats updated to 0.19.0 so I'm assuming this works now
