### ISSUE TITLE
CATS Eye tracking compatibility is broken in the latest KK plugin

### ISSUE THREAD

**Issue by naminode** [FlailingFog/KK-Blender-Shader-Pack#28]
Getting this error after updating to the latest KK plugin. Tried creating eye tracking test with cats.

![image](https://user-images.githubusercontent.com/88361811/129493985-5d3a522c-0747-4fc5-b575-7051d312feee.png)

**Comment by FlailingFog** [comment]
The latest version will make the Upper Chest bone appear between the Chest and Neck bone in the hierarchy.  
Try going into edit mode and changing the Neck bone's parent from "Upper Chest" to "Chest" in the bone tab.
![image](https://user-images.githubusercontent.com/65811931/129497597-2da690b3-f87d-40e1-9bd1-1045fd3b8c5f.png)

**Comment by naminode** [comment]
Thanks. The solution works.
