### ISSUE TITLE
Texture/shader mixup with imported accessories

### ISSUE THREAD

**Issue by miyabi-95** [FlailingFog/KK-Blender-Shader-Pack#36]
I decided to import some hair and a hat using the KK script's FBX importer. It's been super convenient considering you can get accessories with their proper bones. At this point i'm stuck on getting an object shaded. It's my character's santa hat, for whatever reason when I join it with the Clothes object after adjusting the shading where i want, it becomes a solid color, without any of the textures I put in place for it.

I don't want to bug you with too many issue posts, hopefully this is the last one i come across while i finish this version of my model! thanks for your help

**Comment by miyabi-95** [comment]
So uh, turns out i was able to figure out this bug myself? very unexpected lol

All I did was joining the Hat with the Clothes object was go into the textures group of the KK Shader and add a UVMap and set the value to "map0" which is apparently the only value that'd work for the hair extensions that I imported.

**Comment by miyabi-95** [comment]
Looks like i was wrong, the KK Plugin seems to be having trouble processing the five accessories that I've imported. I'm not entirely sure what to do but I can present some evidence of this "bug" (in quotes because I could just have made a big mistake while importing):

My model prior to baking
![Screenshot (671)](https://user-images.githubusercontent.com/63174638/132821028-153ef86b-2dcd-4d65-bc24-6bd6d7ae3de8.png)

My model after baking (notice the solid colors)
![Screenshot (677)](https://user-images.githubusercontent.com/63174638/132821074-6eee41c9-c370-4181-83ec-bca9b6b6eee1.png)

The baked material output
![Screenshot (670)](https://user-images.githubusercontent.com/63174638/132821319-65f43ddd-e4ac-479f-826a-65991733835d.png)

Each imported material's nodes
![Screenshot (672)](https://user-images.githubusercontent.com/63174638/132821207-3e3752e1-4ed0-479a-8ac1-107c175f8e4a.png)
![Screenshot (674)](https://user-images.githubusercontent.com/63174638/132821222-b4727851-5204-4ba0-8ac9-1e464adde556.png)
![Screenshot (675)](https://user-images.githubusercontent.com/63174638/132821245-cdc8c8f6-52b4-412e-9f53-6df146165a4e.png)
![Screenshot (676)](https://user-images.githubusercontent.com/63174638/132821275-f86e3305-ad7e-469c-9d6a-9f911d85fa3d.png)

I will note again that when I started importing, I was forced to use a new UVMap value "map0" because I couldn't get them to function properly with the same value as the other materials. Part of me is wondering if something went wrong while importing, i.e. not appending appropriate shaders or something to do with the way I exported textures from SB3U.

Thanks again for your help!

**Comment by miyabi-95** [comment]
Currently making my next attempt, this time adding the accessories via the CATS FBX import function, _before_ applying the KK Shader Pack & Textures folder.

**Comment by miyabi-95** [comment]
Everything was working until I cleaned the armature, which deleted the bones from my accessories.

At this point i'm pretty frustrated and might just figure out how to add bones to a mesh in blender.

**Comment by FlailingFog** [comment]
Do those hair pieces have textures other than the hair shine? If no then it's working the way it's supposed to work, but if you do have additional textures you can probably just rename "map0" to "UVMap"

**Comment by miyabi-95** [comment]
that explains it! i knew the UVMap had something to do with it bc upon switching the value back to UVMap the textures showed up. will keep an eye on that node next attempt!
