### ISSUE TITLE
Add alpha mask to the hair shader.

### ISSUE THREAD

**Issue by MediaMoots** [FlailingFog/KK-Blender-Shader-Pack#37]
Some cards use an alpha mask on the hair to hide sections.

Please see https://github.com/FlailingFog/KK-Blender-Shader-Pack/issues/29#issuecomment-919882223

**Comment by FlailingFog** [comment]
Nice find, but after looking into it I don't think grey's mesh exporter is giving all of the alpha masks (Hair_f_13 on that card for example). And if a hair piece is used multiple times like hair_b_17 then it only appears to give one of the two alphamasks. It'd be hard to automate this with those two

**Comment by MediaMoots** [comment]
Ah, but I'm working on getting all the masks/colors/textures in a new Plugin I'm making for KK.
And many more improvements such as only exporting meshes that have enabled renders.

:)

Sneak peek of the capability of said plugin.
![image](https://user-images.githubusercontent.com/81146974/133893699-b94945e6-0c5f-41e4-ace2-6c108241af3a.png)
![image](https://user-images.githubusercontent.com/81146974/133893719-5f398497-e668-482b-b7d0-5ae4c68e44cb.png)
Clothing colors:
![image](https://user-images.githubusercontent.com/81146974/133893798-ec369b54-a770-45f5-8fe4-9d576ddd8b1b.png)

Body Colors:
![image](https://user-images.githubusercontent.com/81146974/133893781-b928b310-3a55-4689-a2e4-cdd015552f98.png)

So, if you can make a spot for alpha masks that would be great.

**Comment by FlailingFog** [comment]
I've added a spot for alpha masks in the blend file. The import everything button should load it into the textures group as well as add an outline material for hair with alpha masks (similar to how it works for clothes with alpha masks)

>Sneak peek of the capability of said plugin.

Very interesting! Did you get the source for GME to work off of or something?

**Comment by MediaMoots** [comment]
Perfect, this works flawlessly.
