### ISSUE TITLE
Add normal map to the body shader?

### ISSUE THREAD

**Issue by MediaMoots** [FlailingFog/KK-Blender-Shader-Pack#38]
![cf_m_body_NormalMap](https://user-images.githubusercontent.com/81146974/134456975-7a8a7abf-b6ba-4539-959e-9369ea8d70a2.png)

**Comment by FlailingFog** [comment]
I'll add a slot for it, but you can use it by plugging the image color/alpha into the raw shading node, setting Use Normals to 0 and setting Converted map to 1

**Comment by shukenmg** [comment]
> I'll add a slot for it, but you can use it by plugging the image color/alpha into the raw shading node, setting Use Normals to 0 and setting Converted map to 1

Nice, thought so, once there's a slot we can script it.

**Comment by MediaMoots** [comment]
> I'll add a slot for it, but you can use it by plugging the image color/alpha into the raw shading node, setting Use Normals to 0 and setting Converted map to 1

Nice, thought so, once there's a slot we can script it.

**Comment by MediaMoots** [comment]
Umm, there's an issue with the .blend, the body material is duplicated, haha.

**Comment by FlailingFog** [comment]
Whoops, removed it

**Comment by MediaMoots** [comment]
Also found a random image in the .blend that makes importing templates fail.
![image](https://user-images.githubusercontent.com/81146974/134863153-b7cef8bf-1c75-4e2a-8d1b-56be3334b124.png)

**Comment by FlailingFog** [comment]
Got rid of that too

**Comment by matchapuff** [comment]
> I'll add a slot for it, but you can use it by plugging the image color/alpha into the raw shading node, setting Use Normals to 0 and setting Converted map to 1

How to setting converted map?
Where to setting?
I need pictures to explain.

Have a nice day.
