### ISSUE TITLE
Nail colors

### ISSUE THREAD

**Issue by MediaMoots** [FlailingFog/KK-Blender-Shader-Pack#40]
For some reason, the nail color taken straight from KK does not match what is shown in KKBP.
KKBP:
![image](https://user-images.githubusercontent.com/81146974/134611177-f65680e4-87ca-4d6c-acbc-1f5b8efb6e81.png)
KK:
![image](https://user-images.githubusercontent.com/81146974/134611191-9e335484-57c0-4495-bfa1-6b8a300772c8.png)

Is KK using some other way to blend colors?

**Comment by FlailingFog** [comment]
It looks like there's a color you can set in koikatsu for the nail bed (from the blue channel of the body MC mask), and then some separate mask for the nail gloss (check the Nails section)
KKBP only has the nail bed part, I don't know where nail gloss mask could be

**Comment by MediaMoots** [comment]
So, it's not possible to replicate the color with just the Nail Color from KK?
But isn't gloss just that? Gloss/Shiny
It shouldn't add any sort of tint?

**Comment by MediaMoots** [comment]
Some info from discord
https://discord.com/channels/447114928785063977/447133555844448267/870766590881320961

**Comment by MediaMoots** [comment]
What I'm sure of is that the nail color is affected by the skin color.
Try changing the skin color in KK and see.

**Comment by FlailingFog** [comment]
Sorry, I see what you mean. Maybe the nail hue is the nail color and the nail saturation is the amount the color is mixed in? 

>Some info from discord

I see an alpha cutout for the nails on the body detail mask, but it's for the entire nail, not the nail shine part.

**Comment by MediaMoots** [comment]
> Setting the body color to red and the nail color to a full blue or green makes the nails black, so I think it's a multiplication

Seems like it.
There is still a bit of variation between KKBP and KK but it's pretty much negligible.

Example:
KK
![image](https://user-images.githubusercontent.com/81146974/134794178-6a56027c-6df2-489d-b566-a686ac733771.png)

KKBP
![image](https://user-images.githubusercontent.com/81146974/134794180-10c52f12-141d-4694-8a03-aecea01f6c6e.png)

What do you think is the missing color?

**Comment by MediaMoots** [comment]
I think that the color is close enough, I will close this for now.
Feel free to reopen it if you find some more info.
