### ISSUE TITLE
Support for clothing overlays

### ISSUE THREAD

**Issue by MediaMoots** [FlailingFog/KK-Blender-Shader-Pack#41]
Such as this:
![image](https://user-images.githubusercontent.com/81146974/134611947-64372964-8ba7-461b-a183-2b449471a2ad.png)

Textures for overlays are like this:
![cf_m_bot_skirt03 -387246_PatternMask1](https://user-images.githubusercontent.com/81146974/134611982-326cc3e9-43da-48c2-9f80-12ee13019f6b.png)
With colors:
![image](https://user-images.githubusercontent.com/81146974/134612005-bbe2922a-27d6-4412-b8c9-777345de4bdc.png)

**Comment by FlailingFog** [comment]
I've added these for the four color mask inputs

**Comment by MediaMoots** [comment]
Thanks, ill check it out.

**Comment by MediaMoots** [comment]
Wait, how do i use this?

For example, I have this texture from this skirt
![image](https://user-images.githubusercontent.com/81146974/134864891-5b64a450-64cc-4ec4-bdd6-d6ae5f1df09a.png)
![cf_m_bot_skirt01 -365668_PatternMask1](https://user-images.githubusercontent.com/81146974/134864835-beee02dd-302f-423c-8156-5139f81171e5.png)

Do I just put the texture in the Base slot?

**Comment by MediaMoots** [comment]
This is just a suggestion but, wouldn't it be better to have only one texture and one color for patterns?
Or just one UV control for all pattern masks?

**Comment by FlailingFog** [comment]
You put the texture into the green texture group's color mask color you want it to affect, so I'm guessing that's the red color mask slot.

And I don't think so, the three color mask colors all have options for separate patterns, colors and scaling, so up to three can be used at one time (check the Sailor Type top clothing in koikatsu).

**Comment by MediaMoots** [comment]
> You put the texture into the green texture group's color mask color you want it to affect, so I'm guessing that's the red color mask slot.

Nice, thanks.

How do I disable patterns?
Even without a texture, the pattern color affects the shader.

**Comment by FlailingFog** [comment]
It was doing that because I accidentally put a multiply instead a mix for two of the nodes, I also added placeholders for the patterns because the game wants white in the pattern to be the main color and black to be the secondary color

**Comment by MediaMoots** [comment]
Nice, ill check it out.

**Comment by MediaMoots** [comment]
It works! Thanks again.
