### ISSUE TITLE
Skin type strength

### ISSUE THREAD

**Issue by MediaMoots** [FlailingFog/KK-Blender-Shader-Pack#42]
In KK there's a slider that appears to control the blue part of the Line mask thus adding some detail to the boobs, kokan and other places.
![_Export_2021-09-24-11-50-06_cf_m_body_LineMask](https://user-images.githubusercontent.com/81146974/134615536-ba2fb40e-eda7-42ad-bac8-3473243d4e17.png)

KK
![image](https://user-images.githubusercontent.com/81146974/134615657-2c03f4b0-b2e3-4301-9af0-3a4bce337a38.png)

KKBP
![image](https://user-images.githubusercontent.com/81146974/134615674-fb0ae19b-8bac-46a2-b168-cb9e892cd5db.png)

**Comment by MediaMoots** [comment]
About this
https://discord.com/channels/447114928785063977/447116603591622666/890820059272994818

**Comment by FlailingFog** [comment]
The skin type strength was supposed to work with the Optional mask slot but for some reason the slot refused to work.
Instead of finding out why it broke I just redid parts of the body shader. 
* Skin type base is body MC (this seems to be always present)
* Skin type is the blue channel above
* Skin detail is the green channel above

**Comment by MediaMoots** [comment]
Nice that solves pretty much all issues with this.

I noticed that the hands/feet are shaded differently though, any idea why?

KK
![image](https://user-images.githubusercontent.com/81146974/134794048-bcfc8f02-29b5-4dfb-9926-b360e202ab7a.png)
![image](https://user-images.githubusercontent.com/81146974/134794096-51687e04-93e3-483c-9881-5abb023d07cc.png)

KKBP
please ignore the weird texture on the thumb, that's just the pubic hair, haha.
![image](https://user-images.githubusercontent.com/81146974/134794054-57e5cdbd-3734-46cc-8163-4fc47e454894.png)
![image](https://user-images.githubusercontent.com/81146974/134794098-73ff65ff-140f-434f-953f-62e98ba78628.png)

Maybe self-shadowing?

**Comment by FlailingFog** [comment]
From your screenshots, it doesn't look like you have lighting.
Disabling the shadows in koikatsu makes it pretty similar
![image](https://user-images.githubusercontent.com/65811931/135000047-569a20df-2aa9-4d9c-bfa2-1e4c1ac6c7a6.png)

(Though even if you do add lighting, the shading for KKBP won't exactly match the koikatsu shading)

**Comment by MediaMoots** [comment]
> From your screenshots, it doesn't look like you have lighting.
> Disabling the shadows in koikatsu makes it pretty similar
> ![image](https://user-images.githubusercontent.com/65811931/135000047-569a20df-2aa9-4d9c-bfa2-1e4c1ac6c7a6.png)
> 
> (Though even if you do add lighting, the shading for KKBP won't exactly match the koikatsu shading)

Oh nice, sorry, I didn't realize that, haha.
