### ISSUE TITLE
Mouth interior color

### ISSUE THREAD

**Issue by MediaMoots** [FlailingFog/KK-Blender-Shader-Pack#46]
In KK the mouth interior color is set by a Texture
![cf_m_face_00_MainTex](https://user-images.githubusercontent.com/81146974/134634240-812bce0c-2d6c-40ec-9c7b-cdebe6d7719d.png)
Like so.
So, would changing the face shader to accept this texture as the mouth color be better?

**Comment by FlailingFog** [comment]
I didn't know it had a texture, added a slot for it. 
If you want the unmodified mouth texture, then you can set the "Mouth interior multiplier" to pure white.

**Comment by MediaMoots** [comment]
Thank you!
Does the uv map need to be connected?
![image](https://user-images.githubusercontent.com/81146974/134792493-d134931a-3a08-4c4c-8093-8d064cfbffcf.png)

**Comment by FlailingFog** [comment]
No, it should automatically use the single UVMap

**Comment by MediaMoots** [comment]
Ok cool
Thanks!
