### ISSUE TITLE
Eyeline color

### ISSUE THREAD

**Issue by MediaMoots** [FlailingFog/KK-Blender-Shader-Pack#50]
Splitting this into its own issue for tracking. (Feel free to close this if you want.)

Issue:
https://github.com/FlailingFog/KK-Blender-Shader-Pack/issues/22#issuecomment-926315165

Possible solution:
https://github.com/FlailingFog/KK-Blender-Shader-Pack/issues/22#issuecomment-929828845

**Comment by FlailingFog** [comment]
I added your edits. Is that right?

**Comment by MediaMoots** [comment]
I guess so, feel free to test it because I'm not sure if my edit fixes colors for all (it should, but idk)

**Comment by MediaMoots** [comment]
Yup looks good
Just need to change the Invert node to 0.7 then its perfect

![image](https://user-images.githubusercontent.com/81146974/135736811-0602efff-634f-4ca9-926e-aab98aea479a.png)
