### ISSUE TITLE
v5-merger (0c8b0f4) - finalizepmx/cleanarmature error

### ISSUE THREAD

**Issue by Lexiii223** [FlailingFog/KK-Blender-Shader-Pack#54]
I'm currently getting the following error whenever I try to finalize the PMX.

>  Python: Traceback (most recent call last):
>   File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\importing\finalizepmx.py", line 795, in execute
>     bpy.ops.kkb.cleanarmature('INVOKE_DEFAULT')
>   File "E:\Steam\steamapps\common\Blender\2.93\scripts\modules\bpy\ops.py", line 130, in __call__
>     ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
> RuntimeError: Error: Python: Traceback (most recent call last):
>   File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\importing\cleanarmature.py", line 318, in execute
>     reorganize_armature_layers()
>   File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\importing\cleanarmature.py", line 169, in reorganize_armature_layers
>     set_armature_layer(bone, show_layer = 0)
>   File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\importing\cleanarmature.py", line 124, in set_armature_layer
>     bpy.data.armatures[0].bones[bone_name].layers = (
> KeyError: 'bpy_prop_collection[key]: key "cf_j_thumb01_L" not found'
> 
> location: E:\Steam\steamapps\common\Blender\2.93\scripts\modules\bpy\ops.py:130
> 
> 
> 
> location: <unknown location>:-1

After importing in CATS I have verified that this bone does in fact exist.
![image](https://user-images.githubusercontent.com/86023689/138752003-1667faad-fb0f-4f6f-bba0-3bdc5b5820d9.png)

At some point in the process this bone seems to be getting dropped for whatever reason. I've been looking through the source and I haven't discovered the reason yet.

**Comment by FlailingFog** [comment]
There's a weird behavior that causes blender to delete bones if the head and tail are too close to each other, so maybe that happens during one of those three steps and it gets deleted. 

>Is there a reason you need to translate tail.z on line 137?

I was originally rotating the thumbs a different way that made the tail stick up or something, so that's why tail.z was being set. I'll remove this line.

**Comment by Lexiii223** [comment]
> There's a weird behavior that causes blender to delete bones if the head and tail are too close to each other, so maybe that happens during one of those three steps and it gets deleted.
> 
> > Is there a reason you need to translate tail.z on line 137?
> 
> I was originally rotating the thumbs a different way that made the tail stick up or something, so that's why tail.z was being set. I'll remove this line.

Oh that is weird. Like maybe the bones are too small for blender to care about so they just get dropped. Thanks for assistance, your plugin is amazing thanks for all the hard work you've put into it!
