### ISSUE TITLE
Converting and Applying colors turns model solid black.

### ISSUE THREAD

**Issue by EstrangeSonej** [FlailingFog/KK-Blender-Shader-Pack#57]
<img width="660" alt="ex1" src="https://user-images.githubusercontent.com/93623783/139960206-2daceaa0-e7a6-4093-b94c-cf2c46f15a7f.PNG">

<img width="652" alt="ex2" src="https://user-images.githubusercontent.com/93623783/139960316-9933fe30-d440-4ec5-86d3-d441cde4e3fc.PNG">

I even tried a default model and the same thing happened. 
If there isn't a fix for this, what can I do alternatively?

**Comment by MediaMoots** [comment]
What blender version are you using?
I suggest using 2.93

**Comment by EstrangeSonej** [comment]
I was on 2.90. updating to 2.93.5 fixed it. Thank you so much!

**Comment by MediaMoots** [comment]
No problem, glad you could fix it!
Feel free to close this issue if its fixed.
