### ISSUE TITLE
Bake Materials Error - v5 (3c71ee2)

### ISSUE THREAD

**Issue by Lexiii223** [FlailingFog/KK-Blender-Shader-Pack#60]
Whenever I try to Bake Materials I get the following error. I haven't looked into the cause yet, but I figured I'd post this in case someone already has a solution.

> Python: Traceback (most recent call last):
>   File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\exporting\bakematerials.py", line 366, in execute
>     start_baking(folderpath, resolutionMultiplier)
>   File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\exporting\bakematerials.py", line 317, in start_baking
>     bake_pass(resolutionMultiplier, folderpath, 'light' , 5)
>   File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\exporting\bakematerials.py", line 210, in bake_pass
>     for currentmaterial in objectToBake.data.materials:
> AttributeError: 'Armature' object has no attribute 'materials'
> 
> location: <unknown location>:-1
>

**Comment by Lexiii223** [comment]
This is actually a super easy fix. If you click on the body object the baking process runs without issues. The start_baking method doesn't have any calls to verify what item type is selected. Might want to add a verification or like a drop down to choose which object you want to bake.

**Comment by FlailingFog** [comment]
Good catch! I added a check.
