### ISSUE TITLE
finalizepmx.py Fix Accessories

### ISSUE THREAD

**Issue by LegionInstaller** [FlailingFog/KK-Blender-Shader-Pack#66]
Python: Traceback (most recent call last):
  File "C:\Users\NO\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\importing\finalizepmx.py", line 888, in execute
    fix_accessories()
  File "C:\Users\NO\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\KK-Blender-Shader-Pack-5-merger\importing\finalizepmx.py", line 722, in fix_accessories
    locations_dictionary[mat] = average_location / total_weight
ZeroDivisionError: Vector division: divide by zero error

location: <unknown location>:-1

**Comment by FlailingFog** [comment]
This function is removed in the latest commit since #64 fixes accessories on the exporter side of things

**Comment by LegionInstaller** [comment]
@FlailingFog Is it just like exporting normal models in .fbx or when does the Fix Accessories occur ?

**Comment by FlailingFog** [comment]
Not sure if I understand your question, but the KK exporter was merging accessory bones during export, so I was trying to unmerge the bones after the pmx file was imported into Blender with Fix Accessories. It happened right at the beginning before I removed it.

**Comment by LegionInstaller** [comment]
@FlailingFog Though How Do I export it with the Normal CATS Export ?
sorry for that silly question

**Comment by LegionInstaller** [comment]
@FlailingFog Ah Ok I get that but how do I fix that some Accessories aren't attached to the head anymore , just weight painting it back ?
