### ISSUE TITLE
Export issues on 3.0.0

### ISSUE THREAD

**Issue by Awesome3475** [FlailingFog/KK-Blender-Shader-Pack#70]
Seems there's trouble when trying to Bake materials in 3.0 - may just be incompatible but the images look strange.
![Screenshot 2021-11-12 113347](https://user-images.githubusercontent.com/6384248/141524571-4821a15f-20a9-4c66-aaa5-028edb609568.png)

**Comment by FlailingFog** [comment]
I tried this today and it's working properly. Feel free to reopen if it's still happening.
