### ISSUE TITLE
Improvement script: better eye controls

### ISSUE THREAD

**Issue by ilcane87** [FlailingFog/KK-Blender-Shader-Pack#72]
Cause sometimes you just have to make a derped expression. :P

![Pose](https://user-images.githubusercontent.com/34897042/142740921-5fd7f46f-3812-4593-bee6-26ad7388f535.png)

I suppose this would've come in a future update of KKBSP, but I felt like doing it anyway so here goes.
The script adds new separate controls to move pupils individually as well as the usual container to move them both together. Also, unlike the default one, you can resize the widgets without them flying astray because the script creates bones to hold them.
On creation, the widgets will also attempt to resize themselves to fit the distance between the eyes using the eye vertex groups:

![Rest](https://user-images.githubusercontent.com/34897042/142740934-92ec53ea-a1a0-468c-9ec4-3bd3c5ad47d5.png)

Here's the link:

**EDIT: link removed, use this instead:**

https://github.com/FlailingFog/KK-Blender-Shader-Pack/issues/78

Before running the script, you have to be in Object Mode with the Armature selected and active (it should warn you if you aren't).
Ideally you should run this before making radical changes like deleting or renaming existing items, for example after you have just completed the KKBSP import routine; also, make sure that any scale changes to the body are applied before using it.
The original eye controller bone is moved to layer 10 while the new ones will be in layer 0, and the Body's eye modifiers will be retargeted to three different pre-existing bones also in layer 10 (you should not touch these).

Feel free to include this in the plugin if you think it might prove useful.

**Comment by FlailingFog** [comment]
Thank you! I'll check it out.

**Comment by ilcane87** [comment]
You may wanna wait a few days, I'm about to finish the first version of a script that overhauls the armature with Rigify features, and also incorporates these eye controls.

**Comment by ilcane87** [comment]
Closing this as this version had a problem I fixed later on, and is now incorporated in this:

https://github.com/FlailingFog/KK-Blender-Shader-Pack/issues/78
