### ISSUE TITLE
Missing twist bones breaks "Add bone drivers"

### ISSUE THREAD

**Issue by miyabi-95** [FlailingFog/KK-Blender-Shader-Pack#76]
heya, i'm psyched about the v5 exporter and shader pack! but for now i'm still using the old ones since i'm very used to the process. just for clarity of this issue blender is up-to-date on Steam, i have the latest shader pack before the v5 merging and my CATS plugin is 0.19.0.

whilst trying to update her design a bit, i'm having an issue with adding bone drivers to my model. for whatever reason the twist bones of her Cf_D_Wrists disappeared or are hidden somewhere, so the shader pack function can't proceed.

is it possible that the CATS' model fixing isn't responding to the "keep twist bones" checkbox? i made sure it was checked so there's no reason why it'd remove twist bones.
![Screenshot (1126)](https://user-images.githubusercontent.com/63174638/144132853-74e30c3f-d1aa-4f97-935b-33907f5fd898.png)

**Comment by FlailingFog** [comment]
Did you click the "Run after importing" button? That should prevent CATS from deleting the twist bones.

**Comment by yuyuki** [comment]
Hi,

Wowww. You're faster than the light.

Thank fort your help

I will look at atlas and combining textures in one.

And, no, I didn't see the button run after Importing.

I will look at that tomorrow.

Thank for these tricks

Jaufré Devosse

**Comment by miyabi-95** [comment]
you're absolutely right i am a goof and forgot, LMAO

thanks tho!!
